name: Build

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "setup-chrome"
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
        id: setup-chrome

      - name: "Test Chrome"
        run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
          ${{ steps.setup-chrome.outputs.chrome-path }} --version

      - name: "Update Firefox Manifest"
        run: |
          ls -lAh .
          cp -f manifest-firefox.json src/manifest.json
          ls -lAh .

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src
          filename: "{name}-{version}.xpi"

      - name: "Zip Chrome"
        working-directory: "src"
        run: |
          ls -lAh .
          cp -f ../manifest-chrome.json manifest.json
          mkdir -p ../web-ext-artifacts
          zip "../web-ext-artifacts/chrome.zip" -r .

      - name: "Archive Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: web-ext-artifacts/

      - name: "Debug"
        run: |
          ls -lAhR .
